[workspace]
members = ["libwifi", "libwifi_macros"]

[workspace.package]
version = "1.0.0"
authors = ["Ryan Butler"]
description = "80211 Actions"
homepage = "https://github.com/nukesor/libwifi"
repository = "https://github.com/nukesor/libwifi"
documentation = "https://docs.rs/libwifi/"
license = "MIT"
edition = "2021"
rust-version = "1.62"

[package]
name = "wpa_pwn"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
libc = "0.2.149"
nix = { version = "0.27.1", features = ["socket", "ioctl", "net", "fs"] }
nl80211 = "0.0.2"
libwifi = { version = "0.3.1", path = "libwifi" }
radiotap = "1.3.0"
anyhow = "1.0.75"
