[workspace]
members = ["libwifi", "libwifi_macros"]

[workspace.package]
version = "1.0.0"
authors = ["Ryan Butler"]
description = "80211 WPA Attack Tool"
homepage = "https://github.com/nukesor/libwifi"
repository = "https://github.com/nukesor/libwifi"
documentation = "https://docs.rs/libwifi/"
license = "MIT"
edition = "2021"
rust-version = "1.62"

[package]
name = "WPOxide"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
libc = "0.2.149"
nix = { version = "0.27.1", features = ["socket", "ioctl", "net", "fs"] }
libwifi = { version = "0.3.1", path = "libwifi" }
radiotap = "1.3.0"
anyhow = "1.0.75"
neli = "0.6.4"
neli-proc-macros = "0.1.0"
hex = "0.4.3"
rand = "0.8.5"
ctrlc = "3.4.1"
crossterm = "0.27.0"
ratatui = { version = "0.24.0", features = ["all-widgets"]}
chrono = "0.4.31"
